# Generated by Django 5.2.5 on 2025-08-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_epesheet_pillow'),
    ]

    operations = [
        migrations.AddField(
            model_name='epesheet',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='epesheet',
            name='density',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='epesheet',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='epesheet',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
