# Generated by Django 5.2.5 on 2025-08-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_epesheet_color_epesheet_density_epesheet_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epesheet',
            name='color',
        ),
        migrations.RemoveField(
            model_name='epesheet',
            name='density',
        ),
    ]
